# Generated by Django 5.0.1 on 2024-05-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_courses(apps, schema_editor):
    course = apps.get_model('src', 'Course')
    course.objects.create(course_name='BS Computer Science')
    course.objects.create(course_name='BS Information Technology')
    course.objects.create(course_name='BS Information Systems')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('post_text', models.CharField(max_length=800)),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
                ('post_upvotes', models.IntegerField(default=0)),
                ('post_downvotes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('user_image', models.ImageField(default='lebron.jpg', upload_to='profile_images')),
                ('user_bio', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bytehub.course')),
            ],
        ),
        migrations.RunPython(create_initial_courses),
    ]
