# Generated by Django 5.0.1 on 2024-05-05 06:15

from django.db import migrations, models


def create_initial_courses(apps, schema_editor):
    course = apps.get_model('Bytehub', 'Course')
    course.objects.create(course_name='BS Computer Science')
    course.objects.create(course_name='BS Information Technology')
    course.objects.create(course_name='BS Information Systems')


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=800),
        ),
        migrations.RunPython(create_initial_courses),
    ]
