# Generated by Django 5.0.1 on 2024-05-13 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0002_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bytehub.profile'),
        ),
    ]
