# Generated by Django 5.0.1 on 2024-05-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.TextField(default='Anonymous User'),
        ),
    ]
