# Generated by Django 5.0.1 on 2024-05-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0007_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(default='This is the my bio.'),
        ),
    ]
