# Generated by Django 5.0.1 on 2024-05-19 02:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0009_alter_post_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
