# Generated by Django 5.0.1 on 2024-05-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0010_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
