# Generated by Django 5.0.1 on 2024-05-19 05:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0012_remove_profile_id_user_profile_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', ckeditor.fields.RichTextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bytehub.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Bytehub.post')),
            ],
        ),
    ]
