# Generated by Django 5.0.1 on 2024-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bytehub', '0015_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='connections', to='Bytehub.profile'),
        ),
    ]
